// <auto-generated />
using System;
using JobHunter.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobHunter.Infrastructure.Migrations
{
    [DbContext(typeof(JobHunterDbContext))]
    partial class JobHunterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobHunter.Infrastructure.Entities.JobMaterialLinkEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("JobId", "MaterialId")
                        .IsUnique();

                    b.ToTable("JobMaterialLinks");
                });

            modelBuilder.Entity("JobHunter.Infrastructure.Entities.JobOpportunityEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("AskedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFetched")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("EstimatedValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsAutomationPossible")
                        .HasColumnType("bit");

                    b.Property<string>("MachiningProcessInferredCsv")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MachiningProcessInferred");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Metadata");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobLeads");
                });

            modelBuilder.Entity("JobHunter.Infrastructure.Entities.MaterialEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AmsDesignation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Form")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsoDesignation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemperCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnsDesignation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmsDesignation = "AMS 4037",
                            Category = "Aluminum",
                            Form = "Sheet",
                            IsoDesignation = "AlCu4Mg1",
                            Name = "Aluminum 2024-T3",
                            TemperCondition = "T3",
                            UnsDesignation = "A92024"
                        },
                        new
                        {
                            Id = 2,
                            AmsDesignation = "AMS 4035",
                            Category = "Aluminum",
                            Form = "Plate",
                            IsoDesignation = "AlCu4Mg1",
                            Name = "Aluminum 2024-T351",
                            TemperCondition = "T351",
                            UnsDesignation = "A92024"
                        },
                        new
                        {
                            Id = 3,
                            AmsDesignation = "AMS 4027",
                            Category = "Aluminum",
                            Form = "Bar",
                            IsoDesignation = "AlMg1SiCu",
                            Name = "Aluminum 6061-T6",
                            TemperCondition = "T6",
                            UnsDesignation = "A96061"
                        },
                        new
                        {
                            Id = 4,
                            AmsDesignation = "AMS 4027",
                            Category = "Aluminum",
                            Form = "Plate",
                            IsoDesignation = "AlMg1SiCu",
                            Name = "Aluminum 6061-T651",
                            TemperCondition = "T651",
                            UnsDesignation = "A96061"
                        },
                        new
                        {
                            Id = 5,
                            AmsDesignation = "AMS 4045",
                            Category = "Aluminum",
                            Form = "Bar",
                            IsoDesignation = "AlZn5.5MgCu",
                            Name = "Aluminum 7075-T6",
                            TemperCondition = "T6",
                            UnsDesignation = "A97075"
                        },
                        new
                        {
                            Id = 6,
                            AmsDesignation = "AMS 4078",
                            Category = "Aluminum",
                            Form = "Plate",
                            IsoDesignation = "AlZn5.5MgCu",
                            Name = "Aluminum 7075-T651",
                            TemperCondition = "T651",
                            UnsDesignation = "A97075"
                        },
                        new
                        {
                            Id = 7,
                            AmsDesignation = "AMS 4050",
                            Category = "Aluminum",
                            Form = "Plate",
                            IsoDesignation = "AlZn6CuMgZr",
                            Name = "Aluminum 7050-T7451",
                            TemperCondition = "T7451",
                            UnsDesignation = "A97050"
                        },
                        new
                        {
                            Id = 8,
                            AmsDesignation = "AMS 4911",
                            Category = "Titanium",
                            Form = "Bar",
                            IsoDesignation = "TiAl6V4",
                            Name = "Ti-6Al-4V (Grade 5)",
                            TemperCondition = "Annealed",
                            UnsDesignation = "R56400"
                        },
                        new
                        {
                            Id = 9,
                            AmsDesignation = "AMS 4930",
                            Category = "Titanium",
                            Form = "Bar",
                            IsoDesignation = "TiAl6V4 ELI",
                            Name = "Ti-6Al-4V ELI (Grade 23)",
                            TemperCondition = "Annealed",
                            UnsDesignation = "R56401"
                        },
                        new
                        {
                            Id = 10,
                            AmsDesignation = "AMS 4902",
                            Category = "Titanium",
                            Form = "Sheet",
                            IsoDesignation = "Ti-Gr2",
                            Name = "CP Titanium Grade 2",
                            TemperCondition = "Annealed",
                            UnsDesignation = "R50400"
                        },
                        new
                        {
                            Id = 11,
                            AmsDesignation = "AMS 4928",
                            Category = "Titanium",
                            Form = "Forging",
                            IsoDesignation = "TiAl6V4",
                            Name = "Ti-6Al-4V STA",
                            TemperCondition = "STA",
                            UnsDesignation = "R56400"
                        },
                        new
                        {
                            Id = 12,
                            AmsDesignation = "AMS 5663",
                            Category = "Nickel",
                            Form = "Bar",
                            IsoDesignation = "NiCr19Fe19Nb5Mo3",
                            Name = "Inconel 718",
                            TemperCondition = "Aged",
                            UnsDesignation = "N07718"
                        },
                        new
                        {
                            Id = 13,
                            AmsDesignation = "AMS 5666",
                            Category = "Nickel",
                            Form = "Sheet",
                            IsoDesignation = "NiCr22Mo9Nb",
                            Name = "Inconel 625",
                            TemperCondition = "Annealed",
                            UnsDesignation = "N06625"
                        },
                        new
                        {
                            Id = 14,
                            AmsDesignation = "AMS 5544",
                            Category = "Nickel",
                            Form = "Forging",
                            IsoDesignation = "NiCr20Co13Mo4Ti3Al",
                            Name = "Waspaloy",
                            TemperCondition = "Aged",
                            UnsDesignation = "N07001"
                        },
                        new
                        {
                            Id = 15,
                            AmsDesignation = "AMS 5536",
                            Category = "Nickel",
                            Form = "Sheet",
                            IsoDesignation = "NiCr22Fe18Mo",
                            Name = "Hastelloy X",
                            TemperCondition = "Solution Treated",
                            UnsDesignation = "N06002"
                        },
                        new
                        {
                            Id = 16,
                            AmsDesignation = "AMS 4676",
                            Category = "Nickel",
                            Form = "Bar",
                            IsoDesignation = "NiCu30Al",
                            Name = "Monel K-500",
                            TemperCondition = "Age Hardened",
                            UnsDesignation = "N05500"
                        },
                        new
                        {
                            Id = 17,
                            AmsDesignation = "AMS 5513",
                            Category = "Steel",
                            Form = "Sheet",
                            IsoDesignation = "X5CrNi18-10",
                            Name = "304 Stainless Steel",
                            TemperCondition = "Annealed",
                            UnsDesignation = "S30400"
                        },
                        new
                        {
                            Id = 18,
                            AmsDesignation = "AMS 5507",
                            Category = "Steel",
                            Form = "Bar",
                            IsoDesignation = "X2CrNiMo17-12-2",
                            Name = "316L Stainless Steel",
                            TemperCondition = "Annealed",
                            UnsDesignation = "S31603"
                        },
                        new
                        {
                            Id = 19,
                            AmsDesignation = "AMS 5643",
                            Category = "Steel",
                            Form = "Bar",
                            IsoDesignation = "X5CrNiCuNb16-4",
                            Name = "17-4 PH Stainless",
                            TemperCondition = "H900",
                            UnsDesignation = "S17400"
                        },
                        new
                        {
                            Id = 20,
                            AmsDesignation = "AMS 5659",
                            Category = "Steel",
                            Form = "Bar",
                            IsoDesignation = "X5CrNiCuNb15-5",
                            Name = "15-5 PH Stainless",
                            TemperCondition = "H1025",
                            UnsDesignation = "S15500"
                        },
                        new
                        {
                            Id = 21,
                            AmsDesignation = "AMS 5731",
                            Category = "Steel",
                            Form = "Bar",
                            IsoDesignation = "X5NiCrTi26-15",
                            Name = "A286 Iron-Based Super",
                            TemperCondition = "Aged",
                            UnsDesignation = "S66286"
                        },
                        new
                        {
                            Id = 22,
                            AmsDesignation = "AMS 6414",
                            Category = "Steel",
                            Form = "Bar",
                            IsoDesignation = "34CrNiMo6",
                            Name = "4340 Alloy Steel",
                            TemperCondition = "Quenched & Tempered",
                            UnsDesignation = "G43400"
                        },
                        new
                        {
                            Id = 23,
                            AmsDesignation = "AMS 6370",
                            Category = "Steel",
                            Form = "Tube",
                            IsoDesignation = "25CrMo4",
                            Name = "4130 Alloy Steel",
                            TemperCondition = "Normalized",
                            UnsDesignation = "G41300"
                        },
                        new
                        {
                            Id = 24,
                            AmsDesignation = "AMS 6417",
                            Category = "Steel",
                            Form = "Bar",
                            IsoDesignation = "300M",
                            Name = "300M Ultra-High Strength",
                            TemperCondition = "Quenched & Tempered",
                            UnsDesignation = "K44220"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Copper",
                            Form = "Bar",
                            IsoDesignation = "Cu-ETP",
                            Name = "Copper C110 (ETP)",
                            TemperCondition = "Half Hard",
                            UnsDesignation = "C11000"
                        },
                        new
                        {
                            Id = 26,
                            AmsDesignation = "AMS 4533",
                            Category = "Copper",
                            Form = "Bar",
                            IsoDesignation = "CuBe2",
                            Name = "Beryllium Copper C172",
                            TemperCondition = "AT",
                            UnsDesignation = "C17200"
                        },
                        new
                        {
                            Id = 27,
                            AmsDesignation = "AMS 4375",
                            Category = "Magnesium",
                            Form = "Sheet",
                            IsoDesignation = "MgAl3Zn1",
                            Name = "Magnesium AZ31B",
                            TemperCondition = "H24",
                            UnsDesignation = "M11311"
                        });
                });

            modelBuilder.Entity("JobHunter.Infrastructure.Entities.JobMaterialLinkEntity", b =>
                {
                    b.HasOne("JobHunter.Infrastructure.Entities.JobOpportunityEntity", "Job")
                        .WithMany("MaterialLinks")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobHunter.Infrastructure.Entities.MaterialEntity", "Material")
                        .WithMany("JobLinks")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("JobHunter.Infrastructure.Entities.JobOpportunityEntity", b =>
                {
                    b.Navigation("MaterialLinks");
                });

            modelBuilder.Entity("JobHunter.Infrastructure.Entities.MaterialEntity", b =>
                {
                    b.Navigation("JobLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
